
name: Build Electron App

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Python and Visual C++ Build Tools
        run: |
          choco install -y python  # Install Python
          choco install -y visualcpp-build-tools  # Install Visual C++ Build Tools for compiling extensions

      - name: Download and Install ODBC Driver
        shell: pwsh  # Use PowerShell for this step
        run: |
          # Download the ODBC driver using Invoke-WebRequest
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2280794" -OutFile "msodbcsql.msi"
          
          # Check if the file was downloaded
          if (Test-Path "msodbcsql.msi") {
              Write-Host "msodbcsql.msi downloaded successfully"
          } else {
              Write-Error "Failed to download msodbcsql.msi"
              exit 1
          }
          
          # Install the ODBC driver with logging
          Start-Process msiexec.exe -ArgumentList '/i msodbcsql.msi /quiet /passive /norestart IACCEPTMSODBCSQLLICENSETERMS=YES /l*v install.log' -NoNewWindow -Wait
          
          # Check if the installation was successful and print the log contents
          if (Test-Path "install.log") {
              Write-Host "ODBC Driver installation log created. Check install.log for details."
              Get-Content install.log | Write-Host
          } else {
              Write-Error "install.log file not found!"
          }
          
          # Clean up the installer
          Remove-Item msodbcsql.msi

      - name: Upload installation log as artifact
        if: always()  # Ensure this runs even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: odbc-install-log
          path: install.log

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'  # Use a compatible Python version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel

      - name: Install npm dependencies
        run: npm install

      - name: Run dump
        run: npm run dump

      - name: Build Windows executable
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-win
          path: dist/
